export const ADD_POINT = 'ADD_POINT';
export const REMOVE_POINT = 'REMOVE_POINT';
export const EDIT_POINT = 'EDIT_POINT';
export const CLEAR_INPUTS_POINT = 'CLEAR_INPUTS_POINT';
export const UNCLEAR_INPUTS_POINT = 'UNCLEAR_INPUTS_POINT';
